In [5]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import tensorflow as tf

In [7]:
import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR)

In [10]:
print('Using: ')
print("Tensorflow version: ",tf.__version__)

Using: 
Tensorflow version:  2.1.0


# Single Layer Network

In [31]:
#we set the random seed so that things are reproducible
tf.random.set_seed(7)

#create 5 random input features.
features = tf.random.normal((1,5))

#create random weights for our neural network
weights  = tf.random.normal((1,5))

#create a random bias term for our neural network
bias = tf.random.normal((1,1))

print("Features: ",features)
print("weights: ",weights)
print("bias: ",bias)

Features:  tf.Tensor([[ 0.5983449   0.06276207  0.14631742  0.48481876 -0.23572342]], shape=(1, 5), dtype=float32)
weights:  tf.Tensor([[-2.2733312  -1.6592104  -0.2633568  -0.80923414  1.0294315 ]], shape=(1, 5), dtype=float32)
bias:  tf.Tensor([[1.5749502]], shape=(1, 1), dtype=float32)


In [32]:
def sigmoid_activation(x):
    return 1/(1+tf.exp(-1*x))

In [33]:
#First, all we have to do is multiply the two tensors we got.
multiplication = tf.matmul(features,weights,transpose_b=True)
#Once we are done with multiplication, our next step is to get the sum.
sum_of_weights_features = tf.reduce_sum(multiplication)

#Now, we just need to add the bias term
input_for_sigmoid = sum_of_weights_features + bias

#we have to pass this to the sigmoid function.
ans = sigmoid_activation(input_for_sigmoid)

print("Sigmoid output is: ",ans)

Sigmoid output is:  tf.Tensor([[0.3628656]], shape=(1, 1), dtype=float32)


In [20]:
#getting to know the shape of the tensors we made.
features.shape

TensorShape([1, 5])

In [23]:
weights.shape

TensorShape([1, 5])

In [25]:
bias.shape

TensorShape([1, 1])

# Multi layer neural network

In [35]:
# set the seed so that the things are reproducible
tf.random.set_seed(7)

#create three input features
features = tf.random.normal((1,3))

#Define the size of each layer in our network.
n_input = features.shape[1] #no of input features.
n_hidden = 2 #hidden units
n_output = 1 #output units

#create random weights connecting input to the hidden layer.
W1  = tf.random.normal((n_input,n_hidden))

#create random weights connecting the hidden layer and the output layer.
W2 = tf.random.normal((n_hidden,n_output))

#create random bias term for hidden and the output layers.
B1 = tf.random.normal((1,n_hidden))
B2 = tf.random.normal((1,n_output))



In [42]:
features_for_hidden_layer = sigmoid_activation(tf.reduce_sum(tf.multiply(n_input,W1))+B1)

In [53]:
output_layer_ans = sigmoid_activation(tf.reduce_sum(tf.multiply(features_for_hidden_layer,W2))+B2)

In [54]:
print(output_layer_ans)

tf.Tensor([[0.10233609]], shape=(1, 1), dtype=float32)


# Numpy to tensorflow and back

In [47]:
a = np.random.rand(4,3)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[0.36023427 0.99032902 0.98753691]
 [0.38484105 0.31740383 0.6407981 ]
 [0.17574729 0.59916708 0.8509532 ]
 [0.72668382 0.80361862 0.34393979]]


In [49]:
b = tf.convert_to_tensor(a)
print(b)
print(type(b))

tf.Tensor(
[[0.36023427 0.99032902 0.98753691]
 [0.38484105 0.31740383 0.6407981 ]
 [0.17574729 0.59916708 0.8509532 ]
 [0.72668382 0.80361862 0.34393979]], shape=(4, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [52]:
c = b.numpy()
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[0.36023427 0.99032902 0.98753691]
 [0.38484105 0.31740383 0.6407981 ]
 [0.17574729 0.59916708 0.8509532 ]
 [0.72668382 0.80361862 0.34393979]]
